name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run linting
      run: make check

    - name: Run tests for docker
      run: make tests

    - name: Run tests for podman
      run: make CQFD_DOCKER=podman PODMAN_USERNS="keep-id" tests

    - name: Run tests for docker using sudo
      run: make CQFD_DOCKER="sudo docker" tests

    - name: Run tests for docker using sudo and a non docker user
      run: |
        sudo usermod -aG sudo nobody
        sudo sh -c 'echo "nobody ALL=(ALL) NOPASSWD: ALL" >>/etc/sudoers.d/nobody'
        sudo runuser -u nobody -- make CQFD_RUN_WITH_SUDO="true" USER="cqfd" HOME="/tmp/cqfd" tests
