name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  test-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Run linting
      run: make check

    - name: Setup binfmt
      run: docker run --privileged --rm tonistiigi/binfmt --install all

    - name: Run tests for docker
      run: make tests

  test-podman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Run linting
      run: make check

    - name: Run tests for podman
      run: make CQFD_DOCKER=podman tests
